### ISSUE TITLE
Extremely slow build with fresh project

### ISSUE THREAD

**Issue by EirikFA** [preactjs-templates/typescript#2]
Generating a fresh project using the CLI with this template the build and development server are extremely slow. Building takes more than two minutes, the same for starting the dev server. This is not a problem using the default Preact CLI template, what could be causing this? Tested on two machines, one with Windows and the other with Ubuntu.

**Comment by tdreyno** [comment]
Also getting this on OSX Mojave

**Comment by Akiyamka** [comment]
First run
```
time yarn build
>  Done in 53.36s.
```
Second run
```
time yarn build
>  Done in 13.47s.
```
Fast enough for me.

Host:
OS: Fedora release 31 x86_64 
CPU: Intel i7-8550U (8) @ 4.000GHz 
SSD ext4

**Comment by daniel-j-h** [comment]
Some more anecdata here: on my X1 Carbon laptop
- a cold `npm run dev` takes ~5s
- a cold `npm run build` takes ~20s

which seems plenty fast to me.

What's interesting through is that subsequent runs of `npm run build` does not seem to take any build artifacts / caches into account. Is there a reason we clean out build artifacts between subsequent `npm run build` runs? Is this a preact cli issue?

**Comment by rschristian** [comment]
I'm going to close this out as it's pretty old.

@daniel-j-h That would be a preact-cli issue, yes.
