### ISSUE TITLE
Test script fails for a newly scaffolded project

### ISSUE THREAD

**Issue by thesobercoder** [preactjs-templates/typescript#39]
Running `yarn test` on a newly scaffolded project results in error.

![image](https://user-images.githubusercontent.com/1915249/88771893-88001980-d19d-11ea-9e7d-04924a3dcffe.png)

**Comment by RyanChristian4427** [comment]
Sorry for the references to this issue that I only now notice are incorrect. My fault. 

Do you have a repo in which you can show this? Because unless you've removed all the test files, this should be working. I cannot reproduce.

**Comment by thesobercoder** [comment]
@RyanChristian4427 I think we can close this issue. Its working fine now. Thanks!

**Comment by prateekbh** [comment]
Thank you @RyanChristian4427
