### ISSUE TITLE
Should this use eslint rather than tslint?

### ISSUE THREAD

**Issue by gavinbarron** [preactjs-templates/typescript#4]
Hi,

I stumbled across this project and found it interesting.

What's the thinking about moving to use eslint instead of tslint for linting by default?

I had a quick experiment and it looks pretty feasible: https://github.com/gavinbarron/typescript/commit/12c6c562c49b31d2a15df9b23696a8d0fdb82279 

Thoughts?

**Comment by ForsakenHarmony** [comment]
You can make a pr if you want to

**Comment by ahuglajbclajep** [comment]
#11 ?

**Comment by reznord** [comment]
Yep, closing this issue.
