### ISSUE TITLE
Prerendered routes' css is not being inlined

### ISSUE THREAD

**Issue by suhas023** [preactjs-templates/typescript#42]
**Do you want to request a feature or report a bug?**
looks like a bug in typescript template. Works fine in default template. 

**What is the current behaviour?**
After building, the css is not inlined for prerendered routes, causing a flicker when the page is loaded.

**If the current behaviour is a bug, please provide the steps to reproduce.**
- preact create typescript my-project
- cd my-project
- Add some random CSS to **/src/routes/home/style.css**
- npm run build

After building, in **/dist/index.html**, there's no CSS related to the style we just added, Even though the HTML of the same route is prerendered.

**What is the expected behaviour?**
Since the HTML for the route is prerendered I'd expect the CSS to be also be inlined. Again, this issue does not exist in the default template.

**Please mention other relevant information.**
Node version: v12.18.1
npm version: 6.14.5
Operating system: Ubuntu 18.10
CLI version: 3.0.1

**Comment by RyanChristian4427** [comment]
Sure enough, I can reproduce. Might be important to point out that one doesn't need to add any CSS as even just the base `home` styles won't be in-lined. 

You might be better off moving this to the [CLI repository](https://github.com/preactjs/preact-cli) as that is more often checked.

**Comment by rschristian** [comment]
@suhas023 

Sorry for the long time without a reply. This should be fixed with Preact-CLI v3.03, which was released on Oct. 1st. Give it a shot if you can, let me know if there's any issues.

**Comment by suhas023** [comment]
@rschristian 
Thanks for the update and the effort. You are correct, it's working as expected now.
