### ISSUE TITLE
The template contains lint errors from the beginning

### ISSUE THREAD

**Issue by termosa** [preactjs-templates/typescript#46]
I setup clean project  using preact-cli and immediately get linter errors:
```
$ npx preact-cli create typescript app
$ cd app
$ nr lint

> app@0.0.0 lint /Users/name/app
> eslint 'src/**/*.{js,jsx,ts,tsx}'

Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.

/Users/name/app/src/components/app.tsx
  10:9   warning  'currentUrl' is assigned a value but never used  @typescript-eslint/no-unused-vars
  11:25  warning  Missing return type on function                  @typescript-eslint/explicit-function-return-type

/Users/name/app/src/components/header/style.css.d.ts
  3:22  error  Interface name must not be prefixed with "I"  @typescript-eslint/interface-name-prefix

/Users/name/app/src/routes/home/style.css.d.ts
  3:22  error  Interface name must not be prefixed with "I"  @typescript-eslint/interface-name-prefix

/Users/name/app/src/routes/notfound/style.css.d.ts
  3:22  error  Interface name must not be prefixed with "I"  @typescript-eslint/interface-name-prefix

/Users/name/app/src/routes/profile/index.tsx
  19:16  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
  25:23  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type

/Users/name/app/src/routes/profile/style.css.d.ts
  3:22  error  Interface name must not be prefixed with "I"  @typescript-eslint/interface-name-prefix

/Users/name/app/src/sw.js
  1:57  error  Replace `'preact-cli/sw/'` with `"preact-cli/sw/"`  prettier/prettier

✖ 9 problems (5 errors, 4 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

Packages information:
```
eslint@7.10.0
typescript@4.0.3
@typescript-eslint/eslint-plugin@4.2.0
```

**Comment by rschristian** [comment]
Is this really an issue? If I get some time I'd like to standardize the rules between this and the default template, but for the moment, you can fix / ignore the warnings.

The `*.css.d.ts` files should be entirely ignored, but the rest are pretty easy fixes if you want to get rid of them.

**Comment by termosa** [comment]
I fixed issues and changed rules to make it possible to support interfaces for imported styles.
But yet it is an issue. I bet that most of users expect to run and go.
Also, I would not ignore any d.ts file. Ignoring them is just like using `any` when you have issues. 
I can push fixes if you are good with new rules.

**Comment by rschristian** [comment]
You should ignore `*.css.d.ts` as they are entirely generated. If you open one you will see `// This file is automatically generated from your CSS. Any edits will be overwritten.` at the top of the file.

But we definitely shouldn't be adding even more rules. I'm going to add a PR here to slash them as I think that's the direction that this template will want to go.

**Comment by termosa** [comment]
Oh, didn't notice that.
That's good!

**Comment by rschristian** [comment]
There's a PR open to fix this. No lint warning/errors are thrown anymore if it gets merged.
