### ISSUE TITLE
Error on production command

### ISSUE THREAD

**Issue by MathieuAndrade** [preactjs-templates/typescript#5]
Hi ! 

I'm testing your awesome template and when i run the developpement command `npm run start:development` it's work perfectly. But when i run the production command `npm run start:production` i get this error :

![image](https://user-images.githubusercontent.com/26581253/57956045-e4a84900-78f7-11e9-9413-d58dfbe34de7.png)

Any ideas ? 

I said that I did not change anything in the configuration 🙂 

OS: Windows 10 
Editor: VSCode
Node 10.15.3
Npm 6.4.1

**Comment by ForsakenHarmony** [comment]
oh this is using preact cli pre, it doesn't have the `serve` command anymore

**Comment by vincentBesseau** [comment]
I have the same issue, can you explain us how to resolve it ?

**Comment by ForsakenHarmony** [comment]
You have to use a static file server of your choice, or move it to the public directory that's hosted by i.e. your backend

**Comment by RyanChristian4427** [comment]
#13 Should have solved this.
