### ISSUE TITLE
Css modules are not generating type definitions on buildscripts

### ISSUE THREAD

**Issue by Javi** [preactjs-templates/typescript#50]
The `build` script does not wait until all .d.ts css type definitions are done being generated before trying to compile, resulting in `TS2307: Cannot find module './style.css' or its corresponding type declarations.` errors on CI builds.

**Comment by rschristian** [comment]
I believe I knew that was a possible problem when implementing the new module generation tool. 

I'm really not a fan of the current implementation, so I'm going to bring it up with some people. In the meantime, you can first run a dev build, which won't error out on TS issues so you can wait until the the loader kicks in and does it's job. Not a great solution, but it'll work.

An alternative would be something like this: https://github.com/mrmckeb/typescript-plugin-css-modules . Theoretically it would remove the need to actually generate the `.css.d.ts` files altogether. If you want to give that a shot I'd love to hear your thoughts, but I'll go looking for something tonight regardless. 

Sorry for the inconvenience.

**Comment by Javi** [comment]
Thanks for the alternative! I'll check it out and see if I can get my project working with it, and report back.

**Comment by rschristian** [comment]
@Javi Do you happen to be a VSCode user? I've written a PR and added a tool that should help with auto-complete, though I run JetBrains IDEs so I'm not sure how the VSCode experience is.

**Comment by Javi** [comment]
I'm a JetBrainiac as well, so for the time being this will likely solve my problems as well. Though it is not ideal as you say, I'll let you know how the other library goes.

**Comment by rschristian** [comment]
This was the library I mentioned actually, and I'd argue it's more ideal than the current offering.

Was just looking for a guinea pig to test this out. Certainly worked well enough in Webstorm for me.

**Comment by Javi** [comment]
Oh I thought you had removed the whole thing and it worked. Well so that's definitely an improvement then, worst case scenario a VSCode user could write a plugin if they absolutely need CSS typings, if any. All people I know who care that much about types go with Webstorm though, so once the PR lands I'd say to close the issue.

**Comment by rschristian** [comment]
I removed the `.css.d.ts` file generation, which is what allowed TS to build and would also give autocomplete help. It was replaced by a generic message to TS that all CSS files would be fine and a plugin to give autocomplete help. Should work on both IDEs (all IDEs) hopefully.

**Comment by rschristian** [comment]
With #47 being merged in this should no longer be an issue, as `.css.d.ts` files are no longer generated. Instead we just use a static definition for all `.css` imports. Editors should be able to pick up the slack from there.
