### ISSUE TITLE
Double rendering pre-rendered pages

### ISSUE THREAD

**Issue by mrbrianevans** [preactjs-templates/typescript#55]
Pre-rendered pages render twice if navigated to directly by URL, if the HTML template has been changed (elements added to the body).

This is due to the main div id being `app`, but preact looks for either the first div, or one with id `preact_root`. A lot more info about this is available on this issue: 

> With the default template, there will be no element with `id="preact_root"`. In this case, we essentially make a "guess", and hydrate starting from the first Element in `<body>`:
> 
> ```html
> <body>
>     <div></div>    
>     <other-stuff-here>
>     <script src="..blah"></script>
> </body>
> ```
> 
> In your case, that first element is definitely not the pre-rendered `<App/>` component, so we're essentially "guessing wrong".
> 
> If you render your app's root JSX element with that `id="preact_root"` prop, we no longer have to guess which element within `<body>` was the pre-rendered HTML, since it's explicitly tagged as the root using an attribute:
> 
> ```html
> <body>
>     <div>this is not the App component's pre-rendered HTML</div>  
> 
>     <div id="preact_root">  
>         <h1>hello from App.js</h1>
>     </div>
> 
>     <script src="..blah"></script>
> </body>
> ```
> 

_Originally posted by @developit in https://github.com/preactjs/preact-cli/issues/1330#issuecomment-662001384_

**Comment by ForsakenHarmony** [comment]
Is this an issue with this template specifically?
Otherwise, I think the original issue you linked is the correct one and this is a duplicate?

**Comment by mrbrianevans** [comment]
This line in the template: 

[`<div id="app">`](https://github.com/preactjs-templates/typescript/blob/d519dcf77700917e20a4e0f7b197032f4dd49945/template/src/components/app.tsx#L11)

should be changed to

```tsx
<div id="preact_root">
```

to avoid the double rendering issue described above, for anyone who uses this template and adds anything else to the html body.

Because Preact assumes that the root element has id `preact_root`, I think it makes sense for the template to match that by default.

**Comment by gianpaj** [comment]
I added a div on the `src/components/app.tsx` file and I got the double pre-rendered. This fixes it.

Good catch @mrbrianevans

**Comment by ForsakenHarmony** [comment]
Ok, should be fixed now
