### ISSUE TITLE
Font Awesome's react component for some reason isn't liked by VSCode (possibly due to types)

### ISSUE THREAD

**Issue by ShadiestGoat** [preactjs-templates/typescript#58]
I'm having a problem where I'm trying to use font awesome's react component, but vscode says that I can't. Their component returns 'JSX.Element'. They get JSX from:
```ts
/// <reference types="react" />
```
This is only a minor problem, since it doesn't affect build, only VSCode doesn't like it, lmao. Here is what it has to say:
```
'FontAwesomeIcon' cannot be used as a JSX component.
  Its return type 'JSX.Element' is not a valid JSX element.
    Type 'Element' is missing the following properties from type 'Element': nodeName, attributes, children
```

**Comment by ShadiestGoat** [comment]
Ah, update, `preact build` doesn't like this either

**Comment by rschristian** [comment]
See https://github.com/preactjs/preact/issues/2748. This will solve your issue:

```typescript
// src/types.d.ts
import React from 'react'

declare global {
    namespace React {
        interface ReactElement {
            nodeName: any
            attributes: any
            children: any
        }
    }
}
```

This issue tracker is for issues with this Preact CLI template btw, issues relating to Preact should go on its repo.

**Comment by ShadiestGoat** [comment]
Ah, thank you and sorry. 
It may be good to add this to the template at some point? Idk
Again thank you!

**Comment by rschristian** [comment]
@ShadiestGoat 

Actually, I wrote that too soon. Try upgrading the Enzyme version to `^3.1.0`, looks to be corrected as of the new major.

**Comment by ShadiestGoat** [comment]
My enzyme version is `^3.11.0`

**Comment by rschristian** [comment]
enzyme adapter, sorry
