### ISSUE TITLE
Don't the rest of the favicons need to be added to the manifest.json?

### ISSUE THREAD

**Issue by ShadiestGoat** [preactjs-templates/typescript#60]
Hey, I'm not too sure on this, but don't the rest of the 4 icons need to be added to the manifest.json file? Cause I see 2 of them are there, but like the other 4 aren't...

**Comment by ForsakenHarmony** [comment]
Should be fine, the `manifest.json` is only really used for PWA installs, so it just need an icon for the desktop and a splash icon
