### ISSUE TITLE
tsconfig not aligned with the docs

### ISSUE THREAD

**Issue by drzamich** [preactjs-templates/typescript#70]
Hi! I noticed that the preact-specific compiler options in tsconfig are not aligned with what is outlined in the [docs](https://preactjs.com/guide/v10/typescript). Don't know for sure if it's an issue, but it's clearly a bit confusing so I wanted to flag it here.

**Comment by rschristian** [comment]
Sorry, what are you referring to? That we don't use the automatic transform?

The docs show what you can use in newer versions of TS. By no means do you have to use it.

**Comment by drzamich** [comment]
Hi @rschristian. Yes, I am referring to the `"jsx[...]"` compiler options mentioned in the docs. As I said - I suspected that isn't a major issue that breaks builds or something but thought it would be nice to have consistency. Again, just wanted to flag it here, as I lack knowledge such as implications of the Preact-CLI that might impact this.

**Comment by rschristian** [comment]
I don't understand what inconsistency you're referring to. We use the older method of transpiling JSX is all.

Both are valid and will continue to be into the foreseeable future. Preact's docs aren't saying _you should_ use the runtime transform if you're on newer versions of TS, but that _you could_.

**Comment by drzamich** [comment]
Well to me they explicitly say neither _you should_ nor _you could_. Apparently everyone understands differently what `< 4.1.1` and `>= 4.1.1` means in the comments.

**Comment by rschristian** [comment]
The runtime JSX transform, in case you're unaware, doesn't actually introduce any real advantage. The feature is just a slightly altered transpilation.

That doc section shows how you could use either, but as the feature (JSX transformation) happens with both, it doesn't matter which one you actually choose (minus odd situations like this, in which Preact-CLI might also need to be aware of your choice).

We're working on v4 of CLI, so thanks for mentioning this. Might switch over to using the newer transform as that seems to be a tad more popular these days. Or maybe we can easily support both without a major. I'll have to look into it a bit more and see if our tools can handle that.

**Comment by rschristian** [comment]
Interesting, so it seems `@babel/preset-typescript` (which we use for compiling TS in `preact-cli`) actually handles the `tsconfig.json` settings just fine. I'm not confident that won't break in some fashion, so I'd hesitate to update this template at the moment even though everything seems to be working.

We'll definitely revisit this soon though, I want to support both.
