### ISSUE TITLE
`npm run build` broken

### ISSUE THREAD

**Issue by gitpushdashf** [preactjs-templates/typescript#71]
I ran `npx preact-cli create typescript preact-ts`, and `npm run build` is failing without any changes to the source. `npm run dev` did work, however.

```
preact-ts % npm run build

> preact-ts@0.0.0 build
> preact build

✖ ERROR ./tests/__mocks__/setupTests.ts
ERROR in ./tests/__mocks__/setupTests.ts(5,5):
TS2322: Type 'Adapter' is not assignable to type 'EnzymeAdapter'.
  The types returned by 'createElement(...)' are incompatible between these types.
    Type 'VNode<any>' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>>'.
```

**Comment by rschristian** [comment]
See https://github.com/preactjs/enzyme-adapter-preact-pure/issues/161

For now, you can remove the test dir from your `tsconfig.json`

**Comment by gitpushdashf** [comment]
That worked! Thank you!

**Comment by rschristian** [comment]
Hopefully this will be resolved in the next couple of days, sorry for the inconvenience.

Release weeks are always a bit turbulent 😅

**Comment by gitpushdashf** [comment]
Ha, I understand. Would you like me to leave this open or close it out?

**Comment by rschristian** [comment]
Open is good. Might catch others who run into it.

**Comment by gitpushdashf** [comment]
This works! Thank you so much!
