### ISSUE TITLE
"Cannot find name 'h' with ts-loader"

### ISSUE THREAD

**Issue by tot-ra** [preactjs-templates/typescript#78]
Hey. I kept getting this error, related probably to https://github.com/preactjs/preact/issues/3180 and https://github.com/preactjs-templates/typescript/blob/master/template/tsconfig.json#L8 lines..

After changing tsconfig to
```
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact",
  }
```

the problem went away. Do you think it would be ok to update the template?

**Comment by rschristian** [comment]
No, this is not a correct change to make.

Preact-CLI uses the classic JSX transform (in v3, this will change in v4) which means compiling to `h()` calls. As such, you _should_ be importing `h` into every JSX/TSX file you have. However, as a convenience thing, we use Webpack's [ProvidePlugin to inject `h` and `Fragment` imports into all modules automatically](https://github.com/preactjs/preact-cli/blob/bea4f50a9eb9f56d3a52430d5b1c05834414d56a/packages/cli/src/lib/webpack/webpack-base-config.js#L329-L332). Think of this as a poor man's runtime transform (and much older). This does not play nicely with TS though and there's no way around that.

Altering the `tsconfig.json` in this way is incorrect, as you're telling TS you're using the runtime transform (to avoid needing to import `h`) when in reality we're using the classic transform.
